from evaluation import compute_metrics, print_metrics
from energy_vad_demo import run_energy_vad
from dl_inference import run_dl_inference


def print_comparison_table(results):
    print("\n" + "=" * 68)
    print("VAD Method Comparison")
    print("=" * 68)
    print(f"{'Method':<20} {'F1':>10} {'FAR':>10} {'MISS':>10} {'FP':>8} {'FN':>8}")
    print("-" * 68)

    for name, metrics in results.items():
        print(
            f"{name:<20} "
            f"{metrics['F1']:>10.4f} "
            f"{metrics['FAR']:>10.4f} "
            f"{metrics['MISS']:>10.4f} "
            f"{metrics['FP']:>8d} "
            f"{metrics['FN']:>8d}"
        )


def main():
    print("=" * 68)
    print("CS6140 Voice Activity Detection - Unified Comparison")
    print("=" * 68)

    # ===== Energy baseline =====
    energy_result = run_energy_vad(return_details=True, plot=False)

    metrics_energy_raw = compute_metrics(
        energy_result["y_true"],
        energy_result["y_pred_raw"]
    )
    metrics_energy_smooth = compute_metrics(
        energy_result["y_true"],
        energy_result["y_pred_smooth"]
    )

    print_metrics("Energy VAD - Raw", metrics_energy_raw)
    print_metrics("Energy VAD - Smoothed", metrics_energy_smooth)

    # ===== DL model =====
    # Note:
    # current DL side uses synthetic dataset and its own labels.
    # so this is a pipeline integration demo, not yet a fully matched
    # apples-to-apples comparison on the same real sample.
    dl_result = run_dl_inference(
        strategy="none",
        n_samples=500,
        batch_size=64,
        use_untrained_model=True,
    )

    metrics_dl = compute_metrics(
        dl_result["y_true"],
        dl_result["y_pred"]
    )

    print_metrics("CNN VAD - Synthetic Demo", metrics_dl)

    # ===== Summary table =====
    results = {
        "Energy Raw": metrics_energy_raw,
        "Energy Smoothed": metrics_energy_smooth,
        "CNN Synthetic": metrics_dl,
    }
    print_comparison_table(results)

    print("\nNotes:")
    print("- Energy VAD is evaluated on the real sample.wav clip with manual ground truth.")
    print("- CNN VAD is currently evaluated on synthetic data generated by the DL pipeline.")
    print("- Full project completion requires evaluating both methods on the same dataset.")
    print("- Next step: connect the trained CNN checkpoint and a shared real-data evaluation set.")


if __name__ == "__main__":
    main()